server:
  port: 84

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        # 注册进nacos8848
        server-addr: localhost:8848
    sentinel:
      transport:
        # 在sentinel控制面板显示
        dashboard: localhost:8080
        port: 8719  # 初始端口，不存在网后面+1，直到找到可用

#消费者将去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider

# 激活Sentinel 对Feign 的支持
feign:
  sentinel:
    enabled: true
